name: braw3
description: Simple flashcard prototype with audio and video
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  video_player: ^2.8.6
  shared_preferences: ^2.3.2
  file_picker: ^8.0.0
  path_provider: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/data/cards.json
    - assets/audio/
    - assets/images/
    - assets/video/
